import { SubSection } from '../SubSection.tsx'
import { UnorderedList } from '../../Common/UnorderedList.tsx'
import {
  ChiHarmony,
  ChiJi,
  Coalescence,
  EnvelopingBreath,
  EnvelopingMist,
  JadefireTeachings,
  LifeCocoon,
  MendingProliferation,
  MistWrap,
  PeerIntoPeace,
  RapidDiffusion,
  RenewingMist,
  RisingMist,
  RisingSunKick,
  SecretInfusion,
  StrengthOfTheBlackOx,
  ThunderFocusTea,
  TigerPalm,
} from '../../Common/WowheadLink/Spells.tsx'
import { MasterOfHarmony } from '../../Common/SpecialTexts.tsx'
import { Link } from '../../Common/Link.tsx'
import { healingCooldownsTitle } from './HealingCooldowns.tsx'

export const rampingTitle = 'Ramping'

export function Ramping() {
  return (
    <SubSection title={rampingTitle}>
      <p>
        Mistweaver has many abilities that enhance the healing of your other abilities. Applying
        these buffs ahead of time to increase your healing when it is required is known as ramping
        and is a very important of your healing that mistweaver is currently very reliant on.
      </p>
      <p>
        Start ramping 3-5 seconds before damage goes out. My favorite pattern is (hardcast){' '}
        <EnvelopingMist /> {'>'} <EnvelopingMist /> {'>'} <ThunderFocusTea /> {'>'}{' '}
        <RisingSunKick /> {'>'} <TigerPalm /> {'>'} <RisingSunKick />. This creates two{' '}
        <EnvelopingMist />s and extends them twice, as well as four <ChiHarmony />
        s, and if running <MendingProliferation /> will start spreading quickly. Often I precede all
        this by casting <ChiJi /> for <EnvelopingBreath />.
      </p>
      <p>
        Casting <RenewingMist /> for <ChiHarmony /> can also be good as part of your ramp. Although
        not as impactful as <EnvelopingMist />, it is instant cast and quicker and therefore easier
        to use.
      </p>
      <p>
        After your buffs are applied, simply do whatever other healing you want, following the{' '}
        <Link href={`#${healingCooldownsTitle}`}>section above</Link>. Do not fret about perfectly
        executing your ramp.
      </p>
      <UnorderedList>
        <li>
          <EnvelopingMist />: increases healing by 40% with <MistWrap /> for its duration of 7
          seconds. Hard-casting it is slow, but <ThunderFocusTea />, <ChiJi />,{' '}
          <StrengthOfTheBlackOx />, and <PeerIntoPeace /> can help you get it out quickly.
          Sometimes, it is still worth hard-casting if you have no other options.
        </li>
        <li>
          <ChiHarmony />: increases healing by 25% for 8 seconds. Applied by hard-casting{' '}
          <RenewingMist />, as well as by the ones generated by <RapidDiffusion />, <RisingMist />,
          and <LifeCocoon />.
        </li>
        <li>
          <Coalescence />: increases healing by 20%. Applied by <ThunderFocusTea /> when running{' '}
          <MasterOfHarmony />. Lasts 8 seconds, but can be extended. This is very easily applied to
          the whole group, and is core to <MasterOfHarmony /> healing. Does not affect{' '}
          <JadefireTeachings /> healing.
        </li>
        <li>
          <EnvelopingBreath />: increases healing by 10%. Applied to your group by casting an{' '}
          <EnvelopingMist /> while <ChiJi /> is out.
        </li>
        <li>
          <SecretInfusion />: not really considered ramping per-say, but another buff to give
          yourself before doing significant healing. Using it on versatility or crit is a 15%
          healing increase.
        </li>
      </UnorderedList>
      <p>
        A player with <EnvelopingMist />, <MendingProliferation />, <ChiHarmony />, and{' '}
        <EnvelopingBreath /> is receiving 170% MORE healing!
      </p>
    </SubSection>
  )
}
